apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-demo-service
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-demo-service
            port:
              number: 80
