apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-demo-ingress
spec:
  rules:
  - host: argocd-demo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-demo-service
            port:
              number: 80


# curl --resolve "argocd-demo.example.com:80:$( minikube ip )" -i http://argocd-demo.example.com